FROM centos:centos7


RUN yum -y update \
    && yum -y install curl bzip2 \
    && yum -y install libressl-dev libffi-dev gcc musl-dev libgeos-dev \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local/ \
    && rm -rf /tmp/miniconda.sh \
    && conda install -y python=3.7 \
    && conda update conda \
    # && conda install -y /usr/src/app/requirements.txt \
    && conda install -c conda-forge fastapi uvicorn gunicorn python-multipart \
        geopandas pytest requests \
    && conda clean --all --yes \
    && rpm -e --nodeps curl bzip2 \
    && yum clean all

# CMD ["/bin/bash"]
# # copy project
# COPY . /usr/src/app

# copied from tiangolo/uvicorn-gunicorn-machine-learning-docker

COPY ./start.sh /start.sh
RUN chmod +x /start.sh

COPY ./gunicorn_conf.py /gunicorn_conf.py

COPY ./start-reload.sh /start-reload.sh
RUN chmod +x /start-reload.sh

COPY ./app /app
WORKDIR /app/

ENV PYTHONPATH=/app

EXPOSE 80

# Run the start script, it will check for an /app/prestart.sh script (e.g. for migrations)
# And then will start Gunicorn with Uvicorn
CMD ["/start.sh"]
